# IBM i HTTP Server instance. Name: WEB3003. 
# I created a companion object library: WEB3003
# Feel free to modify according to your own needs.
# Just replace with your own HTTP instance and library names.
# In my example http server and library names were the same.
ServerRoot /www/WEB3003
Listen *:3003

# Recommended for production
TraceEnable Off
Timeout 60
KeepAliveTimeout 5

# Static content - None is required
DocumentRoot /www/WEB3003/htdocs

DirectoryIndex index.html
<Directory /www/WEB3003/htdocs>
    Require all granted
    Options -Indexes
</Directory>

# CGI program directives

# Pass to route using: /api/mypgm/123456 where mypgm is the SQLRPGLE program with the .pgm
# Routes to /QSYS.LIB/WEB3003.LIB/mypgm.PGM
ScriptAliasMatch ^/api/([A-Za-z0-9_]+)(/.*)?$ /QSYS.LIB/WEB3003.LIB/$1.PGM

<Directory /QSYS.LIB/WEB3003.LIB>
    Options +ExecCGI
    Allow From all
    DefaultNetCCSID 1208
    CGIJobCCSID 37
    CGiConvMode BINARY
</Directory>

# Make sure HTTP Authorization header passes
# as HTTP_AUTHORIZATION for the CGI programs.
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [E=HTTP_AUTHORIZATION:%1]

# Logging
AccessFileName .htaccess
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog logs/access_log common
